kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: fixed-build-config
  namespace: florian-ns
spec:
  output:
    to:
      kind: DockerImage
      name: "quay.io/neutron-it/fixed-image:latest"
    pushSecret:
      name: florian-even-pull-secret
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: "ubi-imagestream:latest"
  source:
    type: Git
    git:
      uri: "git@github.com:feven-NIT/fix-image.git"
    contextDir: /
    sourceSecret:
      name: github-deploy-key
